# -------------------------------------
# APPLY - 
# -------------------------------------
apply-azdo-all:
	terragrunt run-all apply --terragrunt-non-interactive --terragrunt-working-dir azdo/
# -------------------------------------
# DESTROY - 
# -------------------------------------

destroy-azdo-all:
	terragrunt run-all destroy --terragrunt-non-interactive --terragrunt-working-dir azdo
